#!/bin/bash
set -x

datadir="/var/www/data"
sudo cp src/csit314.cgi /var/www/cgi-bin/csit314.cgi
sudo cp System/index.html /var/www/html/index.html
sudo cp mockusers.txt $datadir/users.dat

sudo service httpd start
